#!/bin/sh
PYTHONPATH=$PYTHONPATH:$HOME/bin
PATH=$PATH:$HOME/bin
FFTSIZE=2048
BW=250
bn=`basename $1 .dat`

meteor_bb_analyser.py --infile $1 --outfile tmp$$ --fftsize $FFTSIZE --bw $BW >/dev/null 2>&1
fft_raw2asc tmp$$ tmp$$.asc $FFTSIZE $BW >/dev/null 2>&1
rm -f tmp$$
awk '
BEGIN {min = 99999.0; max = -99999.0}
/^$/ {next}
/[0-9]/ {val = $3
         if (val < min) min = val
         if (val > max) max = val
	 }
END {printf ("MIN=%f\n", min+20)
     printf ("MAX=%f\n", max-5)
 }' <tmp$$.asc >vartmp.$$
. ./vartmp.$$
rm -f vartmp.$$
file=tmp$$.asc
ofile=${bn}_bb.png
bw2=`expr $BW / 2`
cat >gnuplot.$$ <<!EOF!
set xlabel "Hz offset"
set xtics 25
set ylabel "Time (Secs)"
set zlabel "Rel Power (dB)"
set title "Log Power Spectrum"
set pm3d map
set term png size 1000,600
set output '$ofile'
set zrange [$MIN:$MAX]
set xrange [-${bw2}:$bw2]
splot '$file'
!EOF!
gnuplot gnuplot.$$
rm -f gnuplot.$$ tmp$$.asc
echo Output file is available in $ofile
